### ISSUE TITLE
output.csv shouldn't overwrite itself

### ISSUE THREAD

**Issue by mikoogla** [IIS-ZPI/ZPI2023_zaoczni_BogoSort#54]
the export name should be more unique (for example add HH::MM or menu function name)

**Comment by rfilipczak** [comment]
Proposed output structure:

choice/prefix_currency_from_to.csv
statistics/
    erfas_usd_2024-01-01_2024-01-04.csv

**Comment by mikoogla** [comment]
resolved in https://github.com/IIS-ZPI/ZPI2023_zaoczni_BogoSort/pull/61
